server:
  port: 9002

spring:
  application:
    name: USER-SERVICE


#ADDED TO BOOTSTRAP FILE
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost